// <auto-generated />
using System;
using Foodo.Infrastructure.Perisistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128093838_clean")]
    partial class clean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foodo.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_LkpAttributes_CreatedDate");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttributeId");

                    b.ToTable("LkpAttributes", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("LkpCode");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpMeasureUnit", b =>
                {
                    b.Property<int>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitOfMeasureId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_LkpMeasureUnits_CreatedDate");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UnitOfMeasureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("UnitOfMeasureId");

                    b.ToTable("LkpMeasureUnits", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpProductDetailsAttribute", b =>
                {
                    b.Property<int>("ProductDetailAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDetailAttributeId"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailAttributeId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("LkpProductDetailsAttributes", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpUserPhoto", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("LkpUserPhotos", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblAdress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_TblAdresses_CreatedDate");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_TblAdresses_IsDefault");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("TblAdresses", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCategoryOfProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("TblCategoryOfProducts", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Burger"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Pizza"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Pasta"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sandwich"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Grill"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "FriedChicken"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Seafood"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Salad"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Soup"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Dessert"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "IceCream"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Juice"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Coffee"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Beverage"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Appetizer"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "MainCourse"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "SideDish"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Shawarma"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Kebab"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Sushi"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Tacos"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Noodles"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "RiceDishes"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Pastry"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Breakfast"
                        });
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCategoryOfRestaurant", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("TblCategoryOfRestaurants", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "FastFood"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "CasualDining"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "FineDining"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cafe"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Bakery"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "DessertShop"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "JuiceBar"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Seafood"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Steakhouse"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Pizzeria"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BBQ"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "FamilyRestaurant"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "HealthyFood"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Vegetarian"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Vegan"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "FoodTruck"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Buffet"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Sandwiches"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Egyptian"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Italian"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "American"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Mexican"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Turkish"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Chinese"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Japanese"
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "Indian"
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Lebanese"
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "Syrian"
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "Greek"
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "French"
                        });
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCustomer", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("TblCustomers", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblDriver", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("TblDrivers", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblMerchant", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("TblMerchants", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_TblOrders_CreatedDate");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CustomerId");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MerchantId");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_TblOrders_OrderDate");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PaidMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("TblOrders", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_TblProducts_CreatedDate");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductsName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("TblProducts", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductCategory", b =>
                {
                    b.Property<int>("productcategoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productcategoryid"));

                    b.Property<int>("categoryid")
                        .HasColumnType("int");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.HasKey("productcategoryid");

                    b.HasIndex("categoryid");

                    b.HasIndex("productid");

                    b.ToTable("TblProductCategories", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductDetail", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDetailId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("TblProductDetails", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("TblProductPhotos", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductsOrder", b =>
                {
                    b.Property<int>("ProductorderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductOrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductorderId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_TblProductsOrders_CreatedDate");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductorderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("TblProductsOrders", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblRestaurantCategory", b =>
                {
                    b.Property<int>("restaurantcategoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restaurantcategoryid"));

                    b.Property<int>("categoryid")
                        .HasColumnType("int");

                    b.Property<string>("restaurantid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("restaurantcategoryid");

                    b.HasIndex("categoryid");

                    b.HasIndex("restaurantid");

                    b.ToTable("TblRestaurantCategories", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.lkpRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("lkpRefreshToken");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d6d2f11c-6482-4b9f-8e59-24e997ac635b",
                            ConcurrencyStamp = "d6d2f11c-6482-4b9f-8e59-24e997ac635b",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "23fd934c-7bcf-40e0-a41e-a253a2d3b557",
                            ConcurrencyStamp = "23fd934c-7bcf-40e0-a41e-a253a2d3b557",
                            Name = "Merchant",
                            NormalizedName = "MERCHANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpCode", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany("LkpCodes")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpProductDetailsAttribute", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.LkpAttribute", "Attribute")
                        .WithMany("LkpProductDetailsAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LkpProductDetailsAttributes_LkpAttributes");

                    b.HasOne("Foodo.Domain.Entities.TblProductDetail", "ProductDetail")
                        .WithMany("LkpProductDetailsAttributes")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LkpProductDetailsAttributes_TblProductDetails");

                    b.HasOne("Foodo.Domain.Entities.LkpMeasureUnit", "UnitOfMeasure")
                        .WithMany("LkpProductDetailsAttributes")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LkpProductDetailsAttributes_LkpMeasureUnits");

                    b.Navigation("Attribute");

                    b.Navigation("ProductDetail");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpUserPhoto", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", "user")
                        .WithOne("UserPhoto")
                        .HasForeignKey("Foodo.Domain.Entities.LkpUserPhoto", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblAdress", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", "User")
                        .WithMany("TblAdresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_TblAdresses_ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCustomer", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TblCustomer")
                        .HasForeignKey("Foodo.Domain.Entities.TblCustomer", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TblCustomer_ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblDriver", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TblDriver")
                        .HasForeignKey("Foodo.Domain.Entities.TblDriver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblMerchant", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TblMerchant")
                        .HasForeignKey("Foodo.Domain.Entities.TblMerchant", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TblMerchant_ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProduct", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblMerchant", "User")
                        .WithMany("TblProducts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TblProducts_TblMerchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductCategory", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblCategoryOfProduct", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodo.Domain.Entities.TblProduct", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductDetail", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblProduct", "Product")
                        .WithMany("TblProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblProductDetails_TblProducts");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductPhoto", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblProduct", "TblProduct")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblProduct");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductsOrder", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblOrder", "Order")
                        .WithMany("TblProductsOrders")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_TblProductsOrders_TblOrders");

                    b.HasOne("Foodo.Domain.Entities.TblProduct", "Product")
                        .WithMany("TblProductsOrders")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_TblProductsOrders_TblProducts");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblRestaurantCategory", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.TblCategoryOfRestaurant", "Category")
                        .WithMany("RestaurantCategories")
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodo.Domain.Entities.TblMerchant", "Restaurant")
                        .WithMany("TblRestaurantCategories")
                        .HasForeignKey("restaurantid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.lkpRefreshToken", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany("lkpRefreshTokens")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Foodo.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foodo.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("LkpCodes");

                    b.Navigation("TblAdresses");

                    b.Navigation("TblCustomer");

                    b.Navigation("TblDriver");

                    b.Navigation("TblMerchant");

                    b.Navigation("UserPhoto");

                    b.Navigation("lkpRefreshTokens");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpAttribute", b =>
                {
                    b.Navigation("LkpProductDetailsAttributes");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.LkpMeasureUnit", b =>
                {
                    b.Navigation("LkpProductDetailsAttributes");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCategoryOfProduct", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblCategoryOfRestaurant", b =>
                {
                    b.Navigation("RestaurantCategories");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblMerchant", b =>
                {
                    b.Navigation("TblProducts");

                    b.Navigation("TblRestaurantCategories");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblOrder", b =>
                {
                    b.Navigation("TblProductsOrders");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProduct", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductPhotos");

                    b.Navigation("TblProductDetails");

                    b.Navigation("TblProductsOrders");
                });

            modelBuilder.Entity("Foodo.Domain.Entities.TblProductDetail", b =>
                {
                    b.Navigation("LkpProductDetailsAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
