// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class ApplicationUser: IdentityUser
{

    public virtual ICollection<TblAdress> TblAdresses { get; set; } = new List<TblAdress>();

    public virtual TblCustomer TblCustomer { get; set; }

    public virtual TblMerchant TblMerchant { get; set; }
}