// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class ApplicationUser: IdentityUser
{


    public virtual TblCustomer TblCustomer { get; set; }

    public virtual TblMerchant TblMerchant { get; set; }
    public virtual ICollection<TblAdress> TblAdresses { get; set; } = new List<TblAdress>();
	public virtual ICollection<lkpRefreshToken> lkpRefreshTokens { get; set; } = new List<lkpRefreshToken>();	
	public virtual ICollection<LkpCodes> LkpCodes { get; set; } = new List<LkpCodes>();
}