// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class LkpProductDetailsAttribute
{
    public int ProductDetailAttributeId { get; set; }

    public int ProductDetailId { get; set; }

    public int UnitOfMeasureId { get; set; }

    public int AttributeId { get; set; }

    public virtual LkpAttribute Attribute { get; set; }

    public virtual TblProductDetail ProductDetail { get; set; }

    public virtual LkpMeasureUnit UnitOfMeasure { get; set; }
}