// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class TblCustomer
{
    public string UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }
	public DateOnly BirthDate { get; set; }

    public virtual ApplicationUser User { get; set; }
}