// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class TblMerchant
{
    public string UserId { get; set; }

    public string StoreName { get; set; }

    public string StoreDescription { get; set; }

    public virtual ICollection<TblProduct> TblProducts { get; set; } = new List<TblProduct>();

    public virtual ApplicationUser User { get; set; }
}