// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class TblOrder
{
    public int OrderId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal TotalPrice { get; set; }

    public decimal Tax { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public string OrderStatus { get; set; }

    public string UserId { get; set; }

    public virtual ICollection<TblProductsOrder> TblProductsOrders { get; set; } = new List<TblProductsOrder>();
}