// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Foodo.Domain.Enums;
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class TblOrder
{
    public int OrderId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal? TotalPrice { get; set; }

    public decimal? Tax { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

	public DateTime CreatedDate { get; set; } = DateTime.Now;

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public OrderState OrderStatus { get; set; }= OrderState.Pending;
	public int BillingAddressId { get; set; }
	public string? DriverId { get; set; }
	public decimal? PaidMoney { get; set; }
	public string CustomerId { get; set; }
	public string MerchantId { get; set; }


	public virtual ICollection<TblProductsOrder>? TblProductsOrders { get; set; } = new List<TblProductsOrder>();
}