// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodo.Domain.Entities;

public partial class TblProduct
{
    public int ProductId { get; set; }

    public string ProductsName { get; set; }

    public string ProductDescription { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string UserId { get; set; }

    public virtual ICollection<TblProductDetail> TblProductDetails { get; set; } = new List<TblProductDetail>();

    public virtual ICollection<TblProductsOrder> TblProductsOrders { get; set; } = new List<TblProductsOrder>();

    public virtual TblMerchant User { get; set; }
}